### DISCUSSION TITLE
A nice card configuration to present the heater values in a useful way

### DISCUSSION THREAD

**Discussion by dominikamann** [dominikamann/oekofen-pellematic-compact#5] [Show and tell]
![grafik](https://user-images.githubusercontent.com/29973737/214558671-814ccbb0-f1c0-402c-b371-81ffbe01478c.png)

Code for lovelace card:

```
type: entities
title: Pellematic Compact
entities:
  - entity: sensor.iconbase
    icon: mdi:water-boiler
    name: >-
      Pellematic Compact (Max, Aktuell, Zwischenbehälter, Vebraucht
      Heute/Gestern)
    type: custom:multiple-entity-row
    entities:
      - entity: sensor.pellet_storage_level_max_2
        name: false
        icon: false
      - entity: sensor.pellet_storage_level
        name: false
        icon: false
      - entity: sensor.pellet_popper_tank
        name: false
        icon: false
      - entity: sensor.pellet_usage_today_2
        name: false
        icon: false
      - entity: sensor.pellet_usage_yesterday_2
        name: false
        icon: false
  - entity: sensor.iconbase
    icon: mdi:water-boiler
    name: Pellematic Compact (Kessel/Soll, Flammraum/Soll)
    type: custom:multiple-entity-row
    entities:
      - entity: sensor.heater_temperature
        name: false
        icon: false
      - entity: sensor.heater_temperature_set
        name: false
        icon: false
      - entity: sensor.heater_flame_chamber_temperature
        name: false
        icon: false
      - entity: sensor.heater_flame_chamber_temperature_set
        name: false
        icon: false
  - entity: sensor.iconbase
    icon: mdi:water-boiler
    name: Warmwasser (Temp-Ein, Temp-Aus, Soll, Pumpe)
    type: custom:multiple-entity-row
    entities:
      - entity: sensor.hot_water_circuit_temperature_on
        name: false
        icon: false
      - entity: sensor.hot_water_circuit_temperature_off
        name: false
        icon: false
      - entity: sensor.hot_water_circuit_temperature_set
        name: false
        icon: false
      - entity: sensor.hot_water_circuit_pump
        name: false
        icon: false
  - entity: sensor.iconbase
    icon: mdi:water-boiler
    name: Puffertank (Oben/Soll, Mitte/Soll, Pumpe)
    type: custom:multiple-entity-row
    entities:
      - entity: sensor.buffer_storage_temperature_upper_area
        name: false
        icon: false
      - entity: sensor.buffer_storage_temperature_upper_area_set
        name: false
        icon: false
      - entity: sensor.buffer_storage_temperature_lower_area
        name: false
        icon: false
      - entity: sensor.buffer_storage_temperature_lower_area_set
        name: false
        icon: false
      - entity: sensor.buffer_storage_pump
        name: false
        icon: false
  - entity: sensor.iconbase
    icon: mdi:water-boiler
    name: Heizkreislauf (Vorlauftemperatur/Soll, Pumpe)
    type: custom:multiple-entity-row
    entities:
      - entity: sensor.heating_circuit_flow_temperature
        name: false
        icon: false
      - entity: sensor.heating_circuit_flow_temperature_set
        name: false
        icon: false
      - entity: sensor.heating_circuit_pump
        name: false
        icon: false
  - entity: sensor.outside_temperature_2
    icon: mdi:water-boiler
    secondary_info: last-updated
    name: Außentemperatur
    type: custom:multiple-entity-row
  - entity: sensor.pellematic_state
    icon: mdi:water-boiler
    name: Pellematic Compact Status
    secondary_info: last-updated
  - entity: sensor.buffer_storage_state
    icon: mdi:water-boiler
    name: Puffertank Status
    secondary_info: last-updated
  - entity: sensor.hot_water_circuit_state
    icon: mdi:water-boiler
    name: Warmwasser Status
    secondary_info: last-updated
  - entity: sensor.heating_circuit_state
    icon: mdi:water-boiler
    name: Heizkreislauf Status
    secondary_info: last-updated
    type: custom:multiple-entity-row
```

Code for configuration/sensors.yaml

```
 - platform: template
    sensors:
      iconbase:
        friendly_name: emptyiconbase
        value_template: >
```

**Comment by dominikamann** [comment]
latest version

```
type: entities
title: Pellematic Compact
entities:
  - entity: sensor.iconbase
    icon: mdi:water-boiler
    name: >-
      Pellematic Compact (Max, Aktuell, Zwischenbehälter, Vebraucht
      Heute/Gestern)
    type: custom:multiple-entity-row
    entities:
      - entity: sensor.pellet_storage_level_max
        name: false
        icon: false
      - entity: sensor.pellet_storage_level
        name: false
        icon: false
      - entity: sensor.pellet_popper_tank
        name: false
        icon: false
      - entity: sensor.pellet_usage_today
        name: false
        icon: false
      - entity: sensor.pellet_usage_yesterday
        name: false
        icon: false
  - entity: sensor.iconbase
    icon: mdi:water-boiler
    name: Pellematic Compact (Kessel/Soll, Flammraum/Soll)
    type: custom:multiple-entity-row
    entities:
      - entity: sensor.heater_temperature
        name: false
        icon: false
      - entity: sensor.heater_temperature_set
        name: false
        icon: false
      - entity: sensor.heater_flame_chamber_temperature
        name: false
        icon: false
      - entity: sensor.heater_flame_chamber_temperature_set
        name: false
        icon: false
  - entity: sensor.iconbase
    icon: mdi:water-boiler
    name: Warmwasser (Temp-Ein, Temp-Aus, Soll, Pumpe)
    type: custom:multiple-entity-row
    entities:
      - entity: sensor.hot_water_circuit_temperature_on
        name: false
        icon: false
      - entity: sensor.hot_water_circuit_temperature_off
        name: false
        icon: false
      - entity: sensor.hot_water_circuit_temperature_set
        name: false
        icon: false
      - entity: sensor.hot_water_circuit_pump
        name: false
        icon: false
  - entity: sensor.iconbase
    icon: mdi:water-boiler
    name: Puffertank (Oben/Soll, Mitte/Soll, Pumpe)
    type: custom:multiple-entity-row
    entities:
      - entity: sensor.buffer_storage_temperature_upper_area
        name: false
        icon: false
      - entity: sensor.buffer_storage_temperature_upper_area_set
        name: false
        icon: false
      - entity: sensor.buffer_storage_temperature_middle_area
        name: false
        icon: false
      - entity: sensor.buffer_storage_temperature_middle_area_set
        name: false
        icon: false
      - entity: sensor.buffer_storage_pump
        name: false
        icon: false
  - entity: sensor.iconbase
    icon: mdi:water-boiler
    name: Heizkreislauf (Vorlauftemperatur/Soll, Pumpe)
    type: custom:multiple-entity-row
    entities:
      - entity: sensor.heating_circuit_1_flow_temperature
        name: false
        icon: false
      - entity: sensor.heating_circuit_1_flow_temperature_set
        name: false
        icon: false
      - entity: sensor.heating_circuit_1_pump
        name: false
        icon: false
  - entity: sensor.outside_temperature
    icon: mdi:water-boiler
    secondary_info: last-updated
    name: Außentemperatur
    type: custom:multiple-entity-row
  - entity: sensor.pellematic_state
    icon: mdi:water-boiler
    name: Pellematic Compact Status
    secondary_info: last-updated
  - entity: sensor.buffer_storage_state
    icon: mdi:water-boiler
    name: Puffertank Status
    secondary_info: last-updated
  - entity: sensor.hot_water_circuit_state
    icon: mdi:water-boiler
    name: Warmwasser Status
    secondary_info: last-updated
  - entity: sensor.heating_circuit_1_state
    icon: mdi:water-boiler
    name: Heizkreislauf Status
    secondary_info: last-updated
    type: custom:multiple-entity-row
  - entity: sensor.heater_starts
  - entity: sensor.heater_runtime_avg
  - entity: sensor.heater_modulation
  - entity: sensor.error_1_2
  - entity: sensor.error_2_2

``` 
![image](https://user-images.githubusercontent.com/29973737/230211026-fd8ca9d6-d73c-47d6-b87a-b532f7ba78c7.png)
![image](https://user-images.githubusercontent.com/29973737/230211055-95e7af08-2c9a-4ee2-9f1c-c06cd97cf6d7.png)
![image](https://user-images.githubusercontent.com/29973737/230211078-3570a1ac-a1e3-4e45-895c-761ec1f4ccdc.png)

**Comment by Macintras** [comment]
Nice Work!
once i have the update to 4.02a I will also look at the integrations, renderings and blueprints automations.
happy easter

**Comment by dominikamann** [comment]
Latest:

```

theme: Backend-selected
title: Heizung
icon: mdi:radiator
badges: []
cards: []
type: sections
sections:
  - type: grid
    cards:
      - type: gauge
        entity: sensor.pelletheizung_pellet_1_storage_level
        needle: true
        name: Pellettank Füllstand
        unit: kg
        severity:
          green: 1500
          yellow: 500
          red: 0
        max: 5000
      - type: custom:apexcharts-card
        graph_span: 6d
        header:
          show: false
        series:
          - entity: sensor.pelletheizung_outside_temperature
            type: line
            name: Outside Temperature
            group_by:
              func: avg
              duration: 1d
          - entity: sensor.pelletheizung_pellet_1_usage_today
            type: line
            name: Pellet usage
            group_by:
              func: max
              duration: 1d
          - entity: sensor.pelletheizung_buffer_storage_temperature_upper_area
            type: line
            name: Puffer (oben)
            group_by:
              func: avg
              duration: 1d
          - entity: sensor.pelletheizung_buffer_storage_temperature_middle_area
            type: line
            name: Puffer (oben)
            group_by:
              func: avg
              duration: 1d
      - chart_type: line
        period: hour
        type: statistics-graph
        entities:
          - sensor.pelletheizung_heating_circuit_1_flow_temperature
        title: Vorlauftemperatur
        stat_types:
          - min
          - max
        days_to_show: 25
        hide_legend: false
        logarithmic_scale: true
  - type: grid
    cards:
      - type: history-graph
        entities:
          - entity: sensor.pelletheizung_heater_1_modulation
        hours_to_show: 24
      - type: tile
        entity: sensor.pelletheizung_heater_1_runtime
        show_entity_picture: false
      - type: tile
        entity: sensor.pelletheizung_heater_1_runtime_avg
      - type: tile
        entity: sensor.pelletheizung_heater_1_starts
      - type: tile
        entity: sensor.pelletheizung_error_1
      - chart_type: line
        period: hour
        type: statistics-graph
        entities:
          - sensor.pelletheizung_buffer_storage_temperature_upper_area
          - sensor.pelletheizung_buffer_storage_temperature_middle_area
        title: Pufferspeicher
        stat_types:
          - min
          - max
          - mean
        days_to_show: 3
        hide_legend: false
  - type: grid
    cards:
      - type: entities
        entities:
          - entity: sensor.iconbase
            icon: mdi:water-boiler
            name: >-
              Pellematic Compact (Max, Aktuell, Zwischenbehälter, Vebraucht
              Heute/Gestern)
            type: custom:multiple-entity-row
            entities:
              - entity: sensor.pelletheizung_pellet_1_storage_level_max
                name: false
                icon: false
              - entity: sensor.pelletheizung_pellet_1_storage_level
                name: false
                icon: false
              - entity: sensor.pelletheizung_pellet_1_popper_tank
                name: false
                icon: false
              - entity: sensor.pelletheizung_pellet_1_usage_today
                name: false
                icon: false
              - entity: sensor.pelletheizung_pellet_1_usage_yesterday
                name: false
                icon: false
          - entity: sensor.iconbase
            icon: mdi:water-boiler
            name: Pellematic Compact (Kessel/Soll, Flammraum/Soll)
            type: custom:multiple-entity-row
            entities:
              - entity: sensor.pelletheizung_heater_1_temperature
                name: false
                icon: false
              - entity: sensor.pelletheizung_heater_1_temperature_set
                name: false
                icon: false
              - entity: sensor.pelletheizung_heater_1_flame_chamber_temperature
                name: false
                icon: false
              - entity: sensor.pelletheizung_heater_1_flame_chamber_temperature_set
                name: false
                icon: false
          - entity: sensor.iconbase
            icon: mdi:water-boiler
            name: Warmwasser (Temp-Ein, Temp-Aus, Soll, Pumpe)
            type: custom:multiple-entity-row
            entities:
              - entity: sensor.pelletheizung_hot_water_circuit_1_temperature_on
                name: false
                icon: false
              - entity: sensor.pelletheizung_hot_water_circuit_1_temperature_off
                name: false
                icon: false
              - entity: sensor.pelletheizung_hot_water_circuit_1_temperature_set
                name: false
                icon: false
              - entity: sensor.pelletheizung_hot_water_circuit_1_pump
                name: false
                icon: false
          - entity: sensor.iconbase
            icon: mdi:water-boiler
            name: Puffertank (Oben/Soll, Mitte/Soll, Pumpe)
            type: custom:multiple-entity-row
            entities:
              - entity: sensor.pelletheizung_buffer_storage_temperature_upper_area
                name: false
                icon: false
              - entity: sensor.pelletheizung_buffer_storage_temperature_upper_area_set
                name: false
                icon: false
              - entity: sensor.pelletheizung_buffer_storage_temperature_middle_area
                name: false
                icon: false
              - entity: >-
                  sensor.pelletheizung_buffer_storage_temperature_middle_area_set
                name: false
                icon: false
              - entity: sensor.pelletheizung_buffer_storage_pump
                name: false
                icon: false
          - entity: sensor.iconbase
            icon: mdi:water-boiler
            name: Heizkreislauf (Vorlauftemperatur/Soll, Pumpe)
            type: custom:multiple-entity-row
            entities:
              - entity: sensor.pelletheizung_heating_circuit_1_flow_temperature
                name: false
                icon: false
              - entity: sensor.pelletheizung_heating_circuit_1_flow_temperature_set
                name: false
                icon: false
              - entity: sensor.pelletheizung_heating_circuit_1_pump
                name: false
                icon: false
          - entity: sensor.pelletheizung_outside_temperature
            icon: mdi:water-boiler
            secondary_info: last-updated
            name: Außentemperatur
            type: custom:multiple-entity-row
          - entity: sensor.pelletheizung_pellematic_state
            icon: mdi:water-boiler
            name: Pellematic Compact Status
            secondary_info: last-updated
          - entity: sensor.pelletheizung_buffer_storage_state
            icon: mdi:water-boiler
            name: Puffertank Status
            secondary_info: last-updated
          - entity: sensor.pelletheizung_hot_water_circuit_1_state
            icon: mdi:water-boiler
            name: Warmwasser Status
            secondary_info: last-updated
          - entity: sensor.pelletheizung_heating_circuit_1_state
            icon: mdi:water-boiler
            name: Heizkreislauf Status
            secondary_info: last-updated
            type: custom:multiple-entity-row
          - entity: sensor.pelletheizung_heater_1_starts
          - entity: sensor.pelletheizung_heater_1_runtime_avg
          - entity: sensor.pelletheizung_heater_1_modulation
          - entity: sensor.pelletheizung_error_1
          - entity: sensor.pelletheizung_error_2

```
